### ISSUE TITLE
Document tagging with classes

### ISSUE THREAD

**Issue by VNeelanshi** [kjschmidt913/NLP#9]
Add these tags to your vocabulary and construct integer representations of the training, validation and test corpora and save these to separate Python lists, which parallel the other integer representations constructed in Step 3. (1.0 pts)

**Comment by kjschmidt913** [comment]
Tagging is working!

Still need to replace tokens with tags. Also need to find the syntax for YEARS as that is a required part of the assignment.

**Comment by kjschmidt913** [comment]
- [X] Tag the document
- [X] find syntax for YEAR and add it to patterns
- [X] replace tokens with their tags for the specified tags

- [x] do this with the actual doc instead of the test data

_**_When do I split the new corpus into training, validation, and test?_**_

- [ ] import Nayan's Vocabulary class

- [ ] Add the new corpus with the doc tags (called new_tokens) to the vocabulary

- [ ] Get the integer representations and save them to separate python lists (one list for each: training, validation, and test)
